### ISSUE TITLE
Symfony 5 Compatibility

### ISSUE THREAD

**Issue by denniserdmann** [ErdmannFreunde/contao-grid-bundle#6]
When updating an from contao 4.10 to 4.11 i got this error:

```
contao/manager-plugin: ...done generating plugin class
> @php vendor/bin/contao-setup

Fatal error: Uncaught ArgumentCountError: Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /contao-latest-ee/vendor/erdmannfreunde/contao-grid-bundle/src/DependencyInjection/Configuration.php on line 23 and at least 1 expected in /contao-latest-ee/vendor/symfony/config/Definition/Builder/TreeBuilder.php:26
Stack trace:
#0 /contao-latest-ee/vendor/erdmannfreunde/contao-grid-bundle/src/DependencyInjection/Configuration.php(23): Symfony\Component\Config\Definition\Builder\TreeBuilder->__construct()
#1 /contao-latest-ee/vendor/symfony/config/Definition/Processor.php(50): ErdmannFreunde\ContaoGridBundle\DependencyInjection\Configuration->getConfigTreeBuilder()
#2 /contao-latest-ee/vendor/symfony/dependency-injection/E in /contao-latest-ee/vendor/symfony/config/Definition/Builder/TreeBuilder.php on line 26
```

I found a similar ticket here: https://github.com/terminal42/contao-url-rewrite/issues/24
and the original ticket here: https://github.com/contao/contao/issues/2844

**Comment by richardhj** [comment]
can you pull the current master branch and re-run scripts?

**Comment by richardhj** [comment]
Fixed in 3c3caad3aa59a76dab0083db7cdc863d81badd51.

**Comment by denniserdmann** [comment]
works like a charm
